/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dentalclinic;

/**
 *
 * @author Maggie
 */
public class dentalServicesFrame extends javax.swing.JFrame {

    /**
     * Creates new form dentalServicesFrame
     */
    public dentalServicesFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        generalPanel.setVisible(false);
        cosmeticPanel.setVisible(false);
        orthodonticsPanel.setVisible(false);
        oralPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orthoButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        nextBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        generalBtn = new javax.swing.JButton();
        orthodonticsBtn = new javax.swing.JButton();
        cosmeticBtn = new javax.swing.JButton();
        oralBtn = new javax.swing.JButton();
        oralPanel = new javax.swing.JPanel();
        oralCheckBox1 = new javax.swing.JCheckBox();
        oralCheckBox2 = new javax.swing.JCheckBox();
        oralCheckBox3 = new javax.swing.JCheckBox();
        oralCheckBox4 = new javax.swing.JCheckBox();
        cosmeticPanel = new javax.swing.JPanel();
        cosmeticCheckBox1 = new javax.swing.JCheckBox();
        cosmeticCheckBox2 = new javax.swing.JCheckBox();
        cosmeticCheckBox3 = new javax.swing.JCheckBox();
        cosmeticCheckBox4 = new javax.swing.JCheckBox();
        generalPanel = new javax.swing.JPanel();
        generalCheckBox1 = new javax.swing.JCheckBox();
        generalCheckBox2 = new javax.swing.JCheckBox();
        generalCheckBox3 = new javax.swing.JCheckBox();
        generalCheckBox4 = new javax.swing.JCheckBox();
        orthodonticsPanel = new javax.swing.JPanel();
        orthodonticsCheckBox1 = new javax.swing.JCheckBox();
        orthodonticsCheckBox2 = new javax.swing.JCheckBox();
        orthodonticsCheckBox3 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        nextBtn.setBorderPainted(false);
        nextBtn.setContentAreaFilled(false);
        nextBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextBtn);
        nextBtn.setBounds(1060, 630, 50, 40);

        returnBtn.setBorderPainted(false);
        returnBtn.setContentAreaFilled(false);
        returnBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        jPanel1.add(returnBtn);
        returnBtn.setBounds(60, 620, 60, 50);

        generalBtn.setBorderPainted(false);
        generalBtn.setContentAreaFilled(false);
        generalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalBtnActionPerformed(evt);
            }
        });
        jPanel1.add(generalBtn);
        generalBtn.setBounds(170, 160, 460, 100);

        orthodonticsBtn.setBorderPainted(false);
        orthodonticsBtn.setContentAreaFilled(false);
        orthodonticsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orthodonticsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orthodonticsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(orthodonticsBtn);
        orthodonticsBtn.setBounds(150, 390, 490, 90);

        cosmeticBtn.setBorderPainted(false);
        cosmeticBtn.setContentAreaFilled(false);
        cosmeticBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cosmeticBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosmeticBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cosmeticBtn);
        cosmeticBtn.setBounds(150, 270, 490, 100);

        oralBtn.setBorderPainted(false);
        oralBtn.setContentAreaFilled(false);
        oralBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oralBtnActionPerformed(evt);
            }
        });
        jPanel1.add(oralBtn);
        oralBtn.setBounds(150, 500, 490, 90);

        oralPanel.setOpaque(false);
        oralPanel.setLayout(null);

        oralCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        oralCheckBox1.setText("Tooth Extraction");
        oralPanel.add(oralCheckBox1);
        oralCheckBox1.setBounds(30, 40, 190, 40);

        oralCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        oralCheckBox2.setText("Dental Implants");
        oralPanel.add(oralCheckBox2);
        oralCheckBox2.setBounds(30, 120, 190, 40);

        oralCheckBox3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        oralCheckBox3.setText("Gum Graft Surgery");
        oralCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oralCheckBox3ActionPerformed(evt);
            }
        });
        oralPanel.add(oralCheckBox3);
        oralCheckBox3.setBounds(30, 200, 190, 40);

        oralCheckBox4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        oralCheckBox4.setText("Root Canal");
        oralPanel.add(oralCheckBox4);
        oralCheckBox4.setBounds(30, 280, 190, 40);

        jPanel1.add(oralPanel);
        oralPanel.setBounds(730, 219, 260, 340);

        cosmeticPanel.setOpaque(false);
        cosmeticPanel.setLayout(null);

        cosmeticCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cosmeticCheckBox1.setText("Teeth Whitening");
        cosmeticPanel.add(cosmeticCheckBox1);
        cosmeticCheckBox1.setBounds(30, 40, 170, 40);

        cosmeticCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cosmeticCheckBox2.setText("Dental Veneers");
        cosmeticPanel.add(cosmeticCheckBox2);
        cosmeticCheckBox2.setBounds(30, 120, 180, 33);

        cosmeticCheckBox3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cosmeticCheckBox3.setText("Dental Bridges");
        cosmeticPanel.add(cosmeticCheckBox3);
        cosmeticCheckBox3.setBounds(30, 200, 160, 40);

        cosmeticCheckBox4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cosmeticCheckBox4.setText("Cosmetic Bonding");
        cosmeticPanel.add(cosmeticCheckBox4);
        cosmeticCheckBox4.setBounds(30, 280, 200, 33);

        jPanel1.add(cosmeticPanel);
        cosmeticPanel.setBounds(730, 220, 260, 340);

        generalPanel.setBackground(new java.awt.Color(245, 245, 246));
        generalPanel.setOpaque(false);
        generalPanel.setLayout(null);

        generalCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        generalCheckBox1.setText("Dental Check-Up");
        generalCheckBox1.setPreferredSize(new java.awt.Dimension(119, 33));
        generalPanel.add(generalCheckBox1);
        generalCheckBox1.setBounds(30, 45, 208, 33);

        generalCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        generalCheckBox2.setText("Dental X-Ray");
        generalCheckBox2.setPreferredSize(new java.awt.Dimension(119, 33));
        generalPanel.add(generalCheckBox2);
        generalCheckBox2.setBounds(30, 122, 174, 33);

        generalCheckBox3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        generalCheckBox3.setText("Tooth Extraction");
        generalCheckBox3.setPreferredSize(new java.awt.Dimension(119, 33));
        generalPanel.add(generalCheckBox3);
        generalCheckBox3.setBounds(30, 204, 207, 33);

        generalCheckBox4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        generalCheckBox4.setText("Fillings");
        generalCheckBox4.setPreferredSize(new java.awt.Dimension(119, 33));
        generalCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalCheckBox4ActionPerformed(evt);
            }
        });
        generalPanel.add(generalCheckBox4);
        generalCheckBox4.setBounds(30, 281, 174, 33);

        jPanel1.add(generalPanel);
        generalPanel.setBounds(730, 220, 260, 340);

        orthodonticsPanel.setOpaque(false);
        orthodonticsPanel.setLayout(null);

        orthoButtonGroup.add(orthodonticsCheckBox1);
        orthodonticsCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        orthodonticsCheckBox1.setText("Ceramic Braces");
        orthodonticsPanel.add(orthodonticsCheckBox1);
        orthodonticsCheckBox1.setBounds(30, 200, 190, 40);

        orthoButtonGroup.add(orthodonticsCheckBox2);
        orthodonticsCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        orthodonticsCheckBox2.setText("Invisalign");
        orthodonticsPanel.add(orthodonticsCheckBox2);
        orthodonticsCheckBox2.setBounds(30, 120, 180, 40);

        orthoButtonGroup.add(orthodonticsCheckBox3);
        orthodonticsCheckBox3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        orthodonticsCheckBox3.setText("Traditonal Braces");
        orthodonticsPanel.add(orthodonticsCheckBox3);
        orthodonticsCheckBox3.setBounds(30, 40, 200, 40);

        jPanel1.add(orthodonticsPanel);
        orthodonticsPanel.setBounds(730, 220, 260, 340);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maggie\\Desktop\\ClearView Images\\dentalServices.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1180, 710);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1172, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generalCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generalCheckBox4ActionPerformed

    private void generalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalBtnActionPerformed
        generalPanel.setVisible(true);
        cosmeticPanel.setVisible(false);
        orthodonticsPanel.setVisible(false);
        oralPanel.setVisible(false);
    }//GEN-LAST:event_generalBtnActionPerformed

    private void cosmeticBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosmeticBtnActionPerformed
        cosmeticPanel.setVisible(true);
        generalPanel.setVisible(false);
        orthodonticsPanel.setVisible(false);
        oralPanel.setVisible(false);
    }//GEN-LAST:event_cosmeticBtnActionPerformed

    private void orthodonticsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orthodonticsBtnActionPerformed
        orthodonticsPanel.setVisible(true);
        generalPanel.setVisible(false);
        cosmeticPanel.setVisible(false);
        oralPanel.setVisible(false);
    }//GEN-LAST:event_orthodonticsBtnActionPerformed

    private void oralCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oralCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oralCheckBox3ActionPerformed

    private void oralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oralBtnActionPerformed
        oralPanel.setVisible(true);
        generalPanel.setVisible(false);
        cosmeticPanel.setVisible(false);
        orthodonticsPanel.setVisible(false);
    }//GEN-LAST:event_oralBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dentalServicesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dentalServicesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dentalServicesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dentalServicesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dentalServicesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cosmeticBtn;
    private javax.swing.JCheckBox cosmeticCheckBox1;
    private javax.swing.JCheckBox cosmeticCheckBox2;
    private javax.swing.JCheckBox cosmeticCheckBox3;
    private javax.swing.JCheckBox cosmeticCheckBox4;
    private javax.swing.JPanel cosmeticPanel;
    private javax.swing.JButton generalBtn;
    private javax.swing.JCheckBox generalCheckBox1;
    private javax.swing.JCheckBox generalCheckBox2;
    private javax.swing.JCheckBox generalCheckBox3;
    private javax.swing.JCheckBox generalCheckBox4;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton oralBtn;
    private javax.swing.JCheckBox oralCheckBox1;
    private javax.swing.JCheckBox oralCheckBox2;
    private javax.swing.JCheckBox oralCheckBox3;
    private javax.swing.JCheckBox oralCheckBox4;
    private javax.swing.JPanel oralPanel;
    private javax.swing.ButtonGroup orthoButtonGroup;
    private javax.swing.JButton orthodonticsBtn;
    private javax.swing.JCheckBox orthodonticsCheckBox1;
    private javax.swing.JCheckBox orthodonticsCheckBox2;
    private javax.swing.JCheckBox orthodonticsCheckBox3;
    private javax.swing.JPanel orthodonticsPanel;
    private javax.swing.JButton returnBtn;
    // End of variables declaration//GEN-END:variables
}
