/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dentalclinic;

import java.awt.Color;

/**
 *
 * @author Maggie
 */
public class employeeLoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form employeeLoginFrame
     */
    public employeeLoginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        employeeID = new javax.swing.JTextField();
        employeePassword = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        signTxt = new javax.swing.JLabel();
        adminBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        employeeID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeeID.setBorder(null);
        jPanel1.add(employeeID);
        employeeID.setBounds(740, 320, 300, 30);

        employeePassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        employeePassword.setBorder(null);
        jPanel1.add(employeePassword);
        employeePassword.setBounds(740, 420, 300, 30);

        loginBtn.setBorderPainted(false);
        loginBtn.setContentAreaFilled(false);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(loginBtn);
        loginBtn.setBounds(780, 510, 160, 50);

        returnBtn.setBorderPainted(false);
        returnBtn.setContentAreaFilled(false);
        returnBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(returnBtn);
        returnBtn.setBounds(40, 50, 70, 50);

        signTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signTxt.setText("For admin access,");
        jPanel1.add(signTxt);
        signTxt.setBounds(750, 600, 200, 30);

        adminBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminBtn.setForeground(new java.awt.Color(120, 139, 255));
        adminBtn.setText("click here.");
        adminBtn.setBorderPainted(false);
        adminBtn.setContentAreaFilled(false);
        adminBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminBtnMouseExited(evt);
            }
        });
        jPanel1.add(adminBtn);
        adminBtn.setBounds(870, 600, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maggie\\Desktop\\ClearView Images\\employeeLogin.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1172, 708);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1172, 708));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBtnMouseEntered
        adminBtn.setForeground(Color.decode("#2c45bc"));
    }//GEN-LAST:event_adminBtnMouseEntered

    private void adminBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBtnMouseExited
        adminBtn.setForeground(Color.decode("#788bff"));
    }//GEN-LAST:event_adminBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeLoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBtn;
    private javax.swing.JTextField employeeID;
    private javax.swing.JPasswordField employeePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton returnBtn;
    private javax.swing.JLabel signTxt;
    // End of variables declaration//GEN-END:variables
}
