/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dentalclinic;

/**
 *
 * @author Maggie
 */
public class patientInformationFrame extends javax.swing.JFrame {

    /**
     * Creates new form patientInformationFrame
     */
    public patientInformationFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        patientName = new javax.swing.JTextField();
        patientBday = new javax.swing.JTextField();
        patientNumber = new javax.swing.JTextField();
        patientEmergencyCon = new javax.swing.JTextField();
        patientAddress = new javax.swing.JTextField();
        patientAllergies = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        nextBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        patientName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientName.setBorder(null);
        jPanel1.add(patientName);
        patientName.setBounds(180, 200, 360, 30);

        patientBday.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientBday.setBorder(null);
        jPanel1.add(patientBday);
        patientBday.setBounds(180, 290, 350, 30);

        patientNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientNumber.setBorder(null);
        jPanel1.add(patientNumber);
        patientNumber.setBounds(180, 380, 350, 30);

        patientEmergencyCon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientEmergencyCon.setBorder(null);
        patientEmergencyCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientEmergencyConActionPerformed(evt);
            }
        });
        jPanel1.add(patientEmergencyCon);
        patientEmergencyCon.setBounds(190, 470, 360, 40);

        patientAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientAddress.setBorder(null);
        jPanel1.add(patientAddress);
        patientAddress.setBounds(190, 560, 360, 30);

        patientAllergies.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        patientAllergies.setBorder(null);
        jPanel1.add(patientAllergies);
        patientAllergies.setBounds(690, 200, 350, 30);

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton1.setText("Pregnant Woman");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(670, 500, 250, 33);

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton2.setText("Senior Citizen");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(670, 410, 180, 33);

        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton3.setText("Person with Disability");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(670, 440, 250, 60);

        nextBtn.setBorderPainted(false);
        nextBtn.setContentAreaFilled(false);
        nextBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextBtn);
        nextBtn.setBounds(1060, 640, 50, 40);

        returnBtn.setBorderPainted(false);
        returnBtn.setContentAreaFilled(false);
        returnBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        jPanel1.add(returnBtn);
        returnBtn.setBounds(60, 630, 60, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maggie\\Desktop\\ClearView Images\\infoFrame.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1170, 710);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1172, 708));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientEmergencyConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientEmergencyConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientEmergencyConActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientInformationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextField patientAddress;
    private javax.swing.JTextField patientAllergies;
    private javax.swing.JTextField patientBday;
    private javax.swing.JTextField patientEmergencyCon;
    private javax.swing.JTextField patientName;
    private javax.swing.JTextField patientNumber;
    private javax.swing.JButton returnBtn;
    // End of variables declaration//GEN-END:variables
}
